language: node_js
node_js:
  - 16.0.0
before_install:
  - yarn install
branches:
  only:
    - master
    - develop
script: 'yarn build'
notifications:
  email:
    recipients:
      - travisci@readlight.me
    on_success: change # default: change
    on_failure: always # default: always
